name: Trigger Vercel Deployment
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Deploy Vercel Site
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} $DEPLOY_HOOK
